packages:
  - apps/*
  - packages/*
catalog:
  "@biomejs/biome": 1.9.4
  "@hono/zod-validator": ^0.4.3
  "@prisma/client": ^6.5.0
  "@prisma/extension-accelerate": ^1.3.0
  "@radix-ui/react-label": ^2.1.2
  "@radix-ui/react-slot": ^1.1.2
  "@rsbuild/core": ^1.2.16
  "@rsbuild/plugin-react": ^1.1.1
  "@rsdoctor/rspack-plugin": ^1.0.0
  "@tailwindcss/postcss": ^4.0.8
  "@tanstack/react-router": ^1.114.27
  "@tanstack/router-plugin": ^1.114.27
  "@tsconfig/node22": ^22
  "@types/node": ^22.13.13
  "@types/react": ^19.0.10
  "@types/react-dom": ^19.0.4
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  hono: ^4.7.5
  lucide-react: ^0.484.0
  prisma: ^6.5.0
  react: ^19.0.0
  react-dom: ^19.0.0
  tailwind-merge: ^3.0.2
  tailwindcss: ^4.0.16
  tw-animate-css: ^1.2.4
  typescript: ^5.8.2
  zod: ^3.24.2
